name: Docker image build and push
on: [push]

jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout repository code
        uses: actions/checkout@v4

      # - name: docker image build
      #   run: docker build -t 21eco12/test-flask-redis:latest .

      # - name: list docker image 
      #   run: docker image ls

      # - name: dockerhub login
      #   run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: push to dockerhub
      #   run: docker image push 21eco12/test-flask-redis:latest

      # 為buildx設定環境
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        # id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Available platforms
        run: echo ${{steps.buildx.outputs.pla}}
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: user/app:latest